_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.11.10
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
algorithm:
    value: PPO
epochs:
    value: 6000
eval_episode_num:
    value: 5
learning_rate:
    value: 0.0002
n_envs:
    value: 4
policy_net:
    value: CnnPolicy
timesteps_per_epoch:
    value: 1000
